language: node_js
node_js:
  - "7"
sudo: required
dist: trusty
before_install:
  - sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
  - npm install
  - npm run installdev
  - npm run bundle-dev
  - cd ../
  - git clone https://github.com/LaserWeb/lw.comm-server.git
  - cd lw.comm-server
  - git checkout electron_bundler
  - npm install
  - ./node_modules/.bin/electron-rebuild
  - npm run dist
after_success:
  - rm -rf node_modules
  - rm -rf dist/*
  - cp ../lw.comm-server/dist/*.AppImage dist/
addons:
  artifacts: true
